# Copyright (c) 2008-2010 Kent State University
# Copyright (c) 2011 Texas A&M University
#
# This file is distributed under the MIT License. See the accompanying file
# LICENSE.txt or http://www.opensource.org/licenses/mit-license.php for terms
# and conditions.

# Turn on testing.
enable_testing()


## Add a unit test with the specified target.
##
##    origin_test(target)
##
## Here, target, is the root of a file in the module. For example, if the
## module contains the files foo.hpp, then it must also contain the files
## foo.cpp and foo.test.cpp. Generating a unit test for the target is done
## using the target name "foo".
##
## Note that the following build targets are generated by this macro:
##
##    ${module}_${target}      -- The program built from ${target}.test.cpp
##    test_${module}_${target} -- The test target used by CTest
##
macro(origin_test target)

  # Get the name of the test driver.
  set(input ${target}.test.cpp)

  # FIXME: Prefix the target with the name of the current module.
  set(exe_target ${ORIGIN_CURRENT_MODULE}_${target})

  # Create the executable target.
  add_executable(${exe_target} ${input})

  # Link against some libraries.
  # FIXME: Which library (or set of libraries) do we need to link against?
  # Eventually, this information should be available when we declare the
  # module and its imports.
  target_link_libraries(${exe_target} ${ORIGIN_CURRENT_LIBRARY_TARGET})

  # Create the test target.
  add_test(test_${exe_target} ${exe_target})

endmacro()

